# Generated by Django 3.1.1 on 2020-09-06 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200906_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
